/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HistoricalTask {
    id: bigint;
    status: TaskStatus;
    result?: string;
    user: Principal;
    description: string;
    taskType: TaskType;
    priority: bigint;
}
export interface TaskView {
    id: bigint;
    status: TaskStatus;
    result?: string;
    user: Principal;
    description: string;
    attemptCount: bigint;
    taskType: TaskType;
    priority: bigint;
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress",
    failed = "failed"
}
export enum TaskType {
    maintenance = "maintenance",
    bugFix = "bugFix",
    featureRequest = "featureRequest",
    optimization = "optimization"
}
export interface backendInterface {
    archiveTask(taskId: bigint): Promise<void>;
    createTask(description: string, taskType: TaskType): Promise<bigint>;
    getArchivedTask(taskId: bigint): Promise<HistoricalTask>;
    getTask(taskId: bigint): Promise<TaskView>;
    incrementAttemptCount(taskId: bigint): Promise<void>;
    isArchivedTaskId(taskId: bigint): Promise<boolean>;
    setTaskResult(taskId: bigint, result: string): Promise<void>;
    updateTaskStatus(taskId: bigint, status: TaskStatus): Promise<void>;
}
import type { HistoricalTask as _HistoricalTask, TaskStatus as _TaskStatus, TaskType as _TaskType, TaskView as _TaskView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async archiveTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.archiveTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.archiveTask(arg0);
            return result;
        }
    }
    async createTask(arg0: string, arg1: TaskType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_TaskType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_TaskType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getArchivedTask(arg0: bigint): Promise<HistoricalTask> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedTask(arg0);
                return from_candid_HistoricalTask_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedTask(arg0);
            return from_candid_HistoricalTask_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: bigint): Promise<TaskView> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_TaskView_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_TaskView_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementAttemptCount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementAttemptCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementAttemptCount(arg0);
            return result;
        }
    }
    async isArchivedTaskId(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isArchivedTaskId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isArchivedTaskId(arg0);
            return result;
        }
    }
    async setTaskResult(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskResult(arg0, arg1);
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_HistoricalTask_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HistoricalTask): HistoricalTask {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TaskView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskView): TaskView {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    result: [] | [string];
    user: Principal;
    description: string;
    attemptCount: bigint;
    taskType: _TaskType;
    priority: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    result?: string;
    user: Principal;
    description: string;
    attemptCount: bigint;
    taskType: TaskType;
    priority: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n5(_uploadFile, _downloadFile, value.status),
        result: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.result)),
        user: value.user,
        description: value.description,
        attemptCount: value.attemptCount,
        taskType: from_candid_TaskType_n8(_uploadFile, _downloadFile, value.taskType),
        priority: value.priority
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    result: [] | [string];
    user: Principal;
    description: string;
    taskType: _TaskType;
    priority: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    result?: string;
    user: Principal;
    description: string;
    taskType: TaskType;
    priority: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n5(_uploadFile, _downloadFile, value.status),
        result: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.result)),
        user: value.user,
        description: value.description,
        taskType: from_candid_TaskType_n8(_uploadFile, _downloadFile, value.taskType),
        priority: value.priority
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : "failed" in value ? TaskStatus.failed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maintenance: null;
} | {
    bugFix: null;
} | {
    featureRequest: null;
} | {
    optimization: null;
}): TaskType {
    return "maintenance" in value ? TaskType.maintenance : "bugFix" in value ? TaskType.bugFix : "featureRequest" in value ? TaskType.featureRequest : "optimization" in value ? TaskType.optimization : value;
}
function to_candid_TaskStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    failed: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value == TaskStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    maintenance: null;
} | {
    bugFix: null;
} | {
    featureRequest: null;
} | {
    optimization: null;
} {
    return value == TaskType.maintenance ? {
        maintenance: null
    } : value == TaskType.bugFix ? {
        bugFix: null
    } : value == TaskType.featureRequest ? {
        featureRequest: null
    } : value == TaskType.optimization ? {
        optimization: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
