/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskType = IDL.Variant({
  'maintenance' : IDL.Null,
  'bugFix' : IDL.Null,
  'featureRequest' : IDL.Null,
  'optimization' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'failed' : IDL.Null,
});
export const HistoricalTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'result' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'taskType' : TaskType,
  'priority' : IDL.Nat,
});
export const TaskView = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'result' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'attemptCount' : IDL.Nat,
  'taskType' : TaskType,
  'priority' : IDL.Nat,
});

export const idlService = IDL.Service({
  'archiveTask' : IDL.Func([IDL.Nat], [], []),
  'createTask' : IDL.Func([IDL.Text, TaskType], [IDL.Nat], []),
  'getArchivedTask' : IDL.Func([IDL.Nat], [HistoricalTask], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [TaskView], ['query']),
  'incrementAttemptCount' : IDL.Func([IDL.Nat], [], []),
  'isArchivedTaskId' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'setTaskResult' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskType = IDL.Variant({
    'maintenance' : IDL.Null,
    'bugFix' : IDL.Null,
    'featureRequest' : IDL.Null,
    'optimization' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'failed' : IDL.Null,
  });
  const HistoricalTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'result' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'taskType' : TaskType,
    'priority' : IDL.Nat,
  });
  const TaskView = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'result' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'attemptCount' : IDL.Nat,
    'taskType' : TaskType,
    'priority' : IDL.Nat,
  });
  
  return IDL.Service({
    'archiveTask' : IDL.Func([IDL.Nat], [], []),
    'createTask' : IDL.Func([IDL.Text, TaskType], [IDL.Nat], []),
    'getArchivedTask' : IDL.Func([IDL.Nat], [HistoricalTask], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [TaskView], ['query']),
    'incrementAttemptCount' : IDL.Func([IDL.Nat], [], []),
    'isArchivedTaskId' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'setTaskResult' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };