/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HistoricalTask {
  'id' : bigint,
  'status' : TaskStatus,
  'result' : [] | [string],
  'user' : Principal,
  'description' : string,
  'taskType' : TaskType,
  'priority' : bigint,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'failed' : null };
export type TaskType = { 'maintenance' : null } |
  { 'bugFix' : null } |
  { 'featureRequest' : null } |
  { 'optimization' : null };
export interface TaskView {
  'id' : bigint,
  'status' : TaskStatus,
  'result' : [] | [string],
  'user' : Principal,
  'description' : string,
  'attemptCount' : bigint,
  'taskType' : TaskType,
  'priority' : bigint,
}
export interface _SERVICE {
  'archiveTask' : ActorMethod<[bigint], undefined>,
  'createTask' : ActorMethod<[string, TaskType], bigint>,
  'getArchivedTask' : ActorMethod<[bigint], HistoricalTask>,
  'getTask' : ActorMethod<[bigint], TaskView>,
  'incrementAttemptCount' : ActorMethod<[bigint], undefined>,
  'isArchivedTaskId' : ActorMethod<[bigint], boolean>,
  'setTaskResult' : ActorMethod<[bigint, string], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];